### PR TITLE
fix(config.go): allow env vars to be shorter names

### LINKED ISSUE #10: app config vars should look like WORKFLOW_MANAGER_ENV_VAR
as per @arschles there's a clean way to use go-friendly field names that point to bash-friendly env var keys:

> there is a envconfig:"MY_ENV_VAR" struct tag that you can use, which makes envconfig look for MY_ENV_VAR and assign its value to that field.

### PR DESCRIPTION
**Pull request by arschles**
Fixes #10

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -4,13 +4,13 @@ import "github.com/kelseyhightower/envconfig"
...
-	APIVersion     string
-	CheckVersions  bool   `default:"true"`
-	DeisNamespace  string `default:"deis"`
+	Port           string `default:"8080" envconfig:"PORT"`
+	Polling        int    `default:"43200" envconfig:"POLL_INTERVAL_SEC"` // 43200 seconds = 12 hours
+	VersionsAPIURL string `envconfig:"VERSIONS_API_URL"`
+	DoctorAPIURL   string `envconfig:"DOCTOR_API_URL"`
+	APIVersion     string `envconfig:"API_VERSION"`
+	CheckVersions  bool   `default:"true" envconfig:"CHECK_VERSIONS"`
+	DeisNamespace  string `default:"deis" envconfig:"CHECK_VERSIONS"`
```
Comment (mboersma) [inline config/config.go]: I think this last struct tag should be `envconfig:"DEIS_NAMESPACE"` right?

Comment (arschles) [inline config/config.go]: yep, good catch - thanks!

Comment (arschles) [inline config/config.go]: fixed in https://github.com/deis/workflow-manager/pull/50/commits/1789e75f9986a484612071cde9eb079dc2963241
