### PR TITLE
bug(k8s): unintentional variable shadowing

### LINKED ISSUE #91: k8s.runningK8sData methods have shadowed variables.
E.g.,

```
// Pods method for runningK8sData
func (rkd *runningK8sData) Pods() ([]*models.K8sResource, error) {
	pods, err := getPods(rkd.podLister)
	if err != nil {
		return nil, err
	}
	ret := make([]*models.K8sResource, len(pods))
	for i, p := range pods {
		pod := &models.K8sResource{
			Data: &p,
		}
		ret[i] = pod
	}
	return ret, nil
}
```

The usage of `&p` in the `for i, p :- range pods` iteration is being shadowed over each loop iteration, resulting in a `ret` slice where all items are duplicates pointing to the final member of the `pods` slice.

There are several instances of this, and each should be remediated. @arschles figured out that by making a copy of the enumeration variable, and then assigning a pointer to *it*, we'll solve this.

### PR DESCRIPTION
**Pull request by jackfrancis**
Enforce block scope heap reference when referring to for-loop enumerated variables by address; otherwise all internal assignments inside for loop refer to the same address: the address of the enumerated variable in the final iteration.

fixes #91

### CODE REVIEW

File: k8s/k8s.go [hunk 1]
```diff
@@ -69,8 +69,9 @@ func (rkd *runningK8sData) DaemonSets() ([]*models.K8sResource, error) {
 	}
 	ret := make([]*models.K8sResource, len(ds))
 	for i, d := range ds {
+		d2 := d // grab a value copy of "d" to enforce block scope heap reference, and avoid shadowing non-block scope "d"
```
Comment (arschles) [inline k8s/k8s.go]: since `d` is a `*models.K8sResource`, this is gonna be a shallow copy. does this code work if you don't deep-copy?

File: k8s/k8s_test.go [hunk 2]
```diff
@@ -0,0 +1,339 @@
...
+						ObjectMeta: api.ObjectMeta{
+							Name: "deis-controller",
+						},
+					},
+				},
+			},
+		},
+	}
+	return c.Setup(t)
+}
```
Comment (arschles) [inline k8s/k8s_test.go]: 🙌 for tests!

File: k8s/k8s.go (hunk 1 above)
Comment (jackfrancis) [inline k8s/k8s.go]: Yep, a simple shallow pointer copy is the intention.
